name: tests

on:
  push:
    branches: [main]
  pull_request:

env:
  php_version: 8.5

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          coverage: none

      - name: Composer install
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare environment
        run: cp .env.example .env && php artisan key:generate

      - name: Test
        run: php artisan test
